### ISSUE TITLE
Scala.rx in Ammonite

### ISSUE THREAD

**Issue by garmonbozzzia** [lihaoyi/scala.rx#78]
When I used scala.Rx in Ammonite.
I did only import, then Var(1), then Var(2)

yury@yury-HP-ProBook-450-G3:~$ amm
Loading...
Welcome to the Ammonite Repl 0.8.1
(Scala 2.12.1 Java 1.8.0_111)
yury-yury@ import $ivy.`com.lihaoyi::scalarx:0.3.2`, rx._ 
import $ivy.$                           , rx._
yury-yury@ Var(1) 
res1: Var[Int] = Var@51(1)
yury-yury@ Var(2) 
cmd2.sc:8: exception during macro expansion: 
scala.ScalaReflectionException: object Internal encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
        at scala.reflect.api.Symbols$SymbolApi.asMethod(Symbols.scala:228)
        at scala.reflect.api.Symbols$SymbolApi.asMethod$(Symbols.scala:222)
        at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:88)
        at derive.Derive.$anonfun$getArgSyms$3(Derive.scala:391)
        at derive.Derive.$anonfun$getArgSyms$3$adapted(Derive.scala:391)
        at scala.collection.Iterator.find(Iterator.scala:981)
        at scala.collection.Iterator.find$(Iterator.scala:978)
        at scala.collection.AbstractIterator.find(Iterator.scala:1406)
        at scala.collection.IterableLike.find(IterableLike.scala:78)
        at scala.collection.IterableLike.find$(IterableLike.scala:77)
        at scala.reflect.internal.Scopes$Scope.find(Scopes.scala:51)
        at derive.Derive.$anonfun$getArgSyms$1(Derive.scala:391)
        at scala.util.Either$RightProjection.flatMap(Either.scala:719)
        at derive.Derive.getArgSyms(Derive.scala:387)
        at derive.Derive.onFail$1(Derive.scala:155)
        at derive.Derive.$anonfun$deriveType$5(Derive.scala:212)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at derive.Derive.rec$1(Derive.scala:185)
        at derive.Derive.deriveType(Derive.scala:230)
        at derive.Derive.derive(Derive.scala:60)
        at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:408)
        at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:408)

            .print(res2, res2, "res2", _root_.scala.None)
                  ^
Compilation Failed

**Comment by Voltir** [comment]
Seems to be fixed in 0.4.0-snapshot (Or latest version of ammonite - not sure who is responsible for this working now)
